/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyBillSec_H_
#define	_MyBillSec_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum MyBillSec_PR {
	MyBillSec_PR_billsec,	/* Member billsec is present */
} MyBillSec_PR;

/* MyBillSec */
typedef struct MyBillSec {
	long	 billsec;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pMyBillSec, MyBillSec_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyBillSec_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyBillSec;

#ifdef __cplusplus
}
#endif

#endif	/* _MyBillSec_H_ */
#include <asn_internal.h>
