/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#include "MyBillSec.h"

static asn_TYPE_member_t asn_MBR_MyBillSec_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MyBillSec, billsec),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"billsec"
		},
};
static const ber_tlv_tag_t asn_DEF_MyBillSec_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MyBillSec_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* billsec */
};
static const uint8_t asn_MAP_MyBillSec_mmap_1[(1 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7)
};
static asn_SET_specifics_t asn_SPC_MyBillSec_specs_1 = {
	sizeof(struct MyBillSec),
	offsetof(struct MyBillSec, _asn_ctx),
	offsetof(struct MyBillSec, _presence_map),
	asn_MAP_MyBillSec_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_MyBillSec_tag2el_1,	/* Same as above */
	1,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_MyBillSec_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_MyBillSec = {
	"MyBillSec",
	"MyBillSec",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MyBillSec_tags_1,
	sizeof(asn_DEF_MyBillSec_tags_1)
		/sizeof(asn_DEF_MyBillSec_tags_1[0]), /* 1 */
	asn_DEF_MyBillSec_tags_1,	/* Same as above */
	sizeof(asn_DEF_MyBillSec_tags_1)
		/sizeof(asn_DEF_MyBillSec_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MyBillSec_1,
	1,	/* Elements count */
	&asn_SPC_MyBillSec_specs_1	/* Additional specs */
};

