/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#include "MyCC-PDU.h"

static asn_TYPE_member_t asn_MBR_MyCC_PDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MyCC_PDU, choice.myRequest),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MyRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"myRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MyCC_PDU, choice.myResponse),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MyResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"myResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MyCC_PDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* myRequest */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* myResponse */
};
static asn_CHOICE_specifics_t asn_SPC_MyCC_PDU_specs_1 = {
	sizeof(struct MyCC_PDU),
	offsetof(struct MyCC_PDU, _asn_ctx),
	offsetof(struct MyCC_PDU, present),
	sizeof(((struct MyCC_PDU *)0)->present),
	asn_MAP_MyCC_PDU_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MyCC_PDU = {
	"MyCC-PDU",
	"MyCC-PDU",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_MyCC_PDU_1,
	2,	/* Elements count */
	&asn_SPC_MyCC_PDU_specs_1	/* Additional specs */
};

