/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#include "MyE164Number.h"

static int
memb_e164_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 11 && size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_MyE164Number_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MyE164Number, e164),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		memb_e164_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"e164"
		},
};
static const ber_tlv_tag_t asn_DEF_MyE164Number_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MyE164Number_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 } /* e164 */
};
static const uint8_t asn_MAP_MyE164Number_mmap_1[(1 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7)
};
static asn_SET_specifics_t asn_SPC_MyE164Number_specs_1 = {
	sizeof(struct MyE164Number),
	offsetof(struct MyE164Number, _asn_ctx),
	offsetof(struct MyE164Number, _presence_map),
	asn_MAP_MyE164Number_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_MyE164Number_tag2el_1,	/* Same as above */
	1,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_MyE164Number_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_MyE164Number = {
	"MyE164Number",
	"MyE164Number",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MyE164Number_tags_1,
	sizeof(asn_DEF_MyE164Number_tags_1)
		/sizeof(asn_DEF_MyE164Number_tags_1[0]), /* 1 */
	asn_DEF_MyE164Number_tags_1,	/* Same as above */
	sizeof(asn_DEF_MyE164Number_tags_1)
		/sizeof(asn_DEF_MyE164Number_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MyE164Number_1,
	1,	/* Elements count */
	&asn_SPC_MyE164Number_specs_1	/* Additional specs */
};

