/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyHeader_H_
#define	_MyHeader_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyHeader */
typedef struct MyHeader {
	long	 cdrServerId;
	long	 transactionId;
	long	 version;
	long	 timestamp;
	OCTET_STRING_t	 hostname;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyHeader;

#ifdef __cplusplus
}
#endif

#endif	/* _MyHeader_H_ */
#include <asn_internal.h>
