/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#include "MyRequestPayload.h"

static asn_TYPE_member_t asn_MBR_MyRequestPayload_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MyRequestPayload, choice.maxsec),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MyRequestMaxsec,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"maxsec"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MyRequestPayload, choice.balance),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MyRequestBalance,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"balance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MyRequestPayload, choice.rate),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MyRequestRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MyRequestPayload, choice.term),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MyRequestTerm,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"term"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MyRequestPayload, choice.status),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"status"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MyRequestPayload_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* maxsec */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* balance */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* rate */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* term */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 } /* status */
};
static asn_CHOICE_specifics_t asn_SPC_MyRequestPayload_specs_1 = {
	sizeof(struct MyRequestPayload),
	offsetof(struct MyRequestPayload, _asn_ctx),
	offsetof(struct MyRequestPayload, present),
	sizeof(((struct MyRequestPayload *)0)->present),
	asn_MAP_MyRequestPayload_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MyRequestPayload = {
	"MyRequestPayload",
	"MyRequestPayload",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_MyRequestPayload_1,
	5,	/* Elements count */
	&asn_SPC_MyRequestPayload_specs_1	/* Additional specs */
};

