/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyResponseBalance_H_
#define	_MyResponseBalance_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NumericString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyResponseBalance */
typedef struct MyResponseBalance {
	NumericString_t	 amount;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyResponseBalance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyResponseBalance;

#ifdef __cplusplus
}
#endif

#endif	/* _MyResponseBalance_H_ */
#include <asn_internal.h>
