/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyResponse_H_
#define	_MyResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MyHeader.h"
#include "MyResponsePayload.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyResponse */
typedef struct MyResponse {
	MyHeader_t	 header;
	MyResponsePayload_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _MyResponse_H_ */
#include <asn_internal.h>
