/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyResponseMaxsec_H_
#define	_MyResponseMaxsec_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyResponseMaxsec */
typedef struct MyResponseMaxsec {
	long	 maxsec;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyResponseMaxsec_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyResponseMaxsec;

#ifdef __cplusplus
}
#endif

#endif	/* _MyResponseMaxsec_H_ */
#include <asn_internal.h>
