/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyRequestPayload_H_
#define	_MyRequestPayload_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MyRequestMaxsec.h"
#include "MyRequestBalance.h"
#include "MyRequestRate.h"
#include "MyRequestTerm.h"
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MyRequestPayload_PR {
	MyRequestPayload_PR_NOTHING,	/* No components present */
	MyRequestPayload_PR_maxsec,
	MyRequestPayload_PR_balance,
	MyRequestPayload_PR_rate,
	MyRequestPayload_PR_term,
	MyRequestPayload_PR_status
} MyRequestPayload_PR;

/* MyRequestPayload */
typedef struct MyRequestPayload {
	MyRequestPayload_PR present;
	union MyRequestPayload_u {
		MyRequestMaxsec_t	 maxsec;
		MyRequestBalance_t	 balance;
		MyRequestRate_t	 rate;
		MyRequestTerm_t	 term;
		NULL_t	 status;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyRequestPayload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyRequestPayload;

#ifdef __cplusplus
}
#endif

#endif	/* _MyRequestPayload_H_ */
#include <asn_internal.h>
