/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyResponsePayload_H_
#define	_MyResponsePayload_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MyResponseMaxsec.h"
#include "MyResponseBalance.h"
#include "MyResponseRate.h"
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MyResponsePayload_PR {
	MyResponsePayload_PR_NOTHING,	/* No components present */
	MyResponsePayload_PR_maxsec,
	MyResponsePayload_PR_balance,
	MyResponsePayload_PR_rate,
	MyResponsePayload_PR_term,
	MyResponsePayload_PR_status
} MyResponsePayload_PR;

/* MyResponsePayload */
typedef struct MyResponsePayload {
	MyResponsePayload_PR present;
	union MyResponsePayload_u {
		MyResponseMaxsec_t	 maxsec;
		MyResponseBalance_t	 balance;
		MyResponseRate_t	 rate;
		NULL_t	 term;
		NULL_t	 status;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyResponsePayload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyResponsePayload;

#ifdef __cplusplus
}
#endif

#endif	/* _MyResponsePayload_H_ */
#include <asn_internal.h>
