/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyRequest_H_
#define	_MyRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MyHeader.h"
#include "MyRequestPayload.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyRequest */
typedef struct MyRequest {
	MyHeader_t	 header;
	MyRequestPayload_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _MyRequest_H_ */
#include <asn_internal.h>
