/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyRequestRate_H_
#define	_MyRequestRate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MyE164Number.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyRequestRate */
typedef struct MyRequestRate {
	MyE164Number_t	 callingNumber;
	MyE164Number_t	 calledNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyRequestRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyRequestRate;

#ifdef __cplusplus
}
#endif

#endif	/* _MyRequestRate_H_ */
#include <asn_internal.h>
