--
-- FreeSWITCH CDR server / fs 'xml_cdrs' + httpd + php scripts / , 2018-04-23
--

CREATE TABLE cdrs (
    id serial PRIMARY KEY NOT NULL,
    call_uid character varying(128) UNIQUE NOT NULL,
    ts timestamp without time zone,
    src character varying(80),
    dst character varying(80),
    clg_nadi integer,
    cld_nadi integer,
    presentation integer,
    screen integer,
    src_context character varying(80),
    dst_context character varying(80),
    billsec integer,
    duration integer,
    incoming_channel character varying(128),
    outgoing_channel character varying(128),
    incoming_codec character varying(16),
    outgoing_codec character varying(16),
    account_code character varying(80),
    hangup_cause character varying(80),
    originate_disposition character varying(80),
    hangup_cause_q850 integer,
    dst_tgroup character varying(80),
    src_tgroup character varying(80),
    uduration bigint,
    billusec bigint,
    rdnis character varying(80),
    rdnis_nadi integer,
    rdnis_screen integer,
    rdnis_presentation integer,
    local_network_addr character varying(16),
    contact_uri character varying(128),
    to_uri character varying(128),
    full_via text,
    remote_media_ip character varying(16),
    remote_media_port integer,
    maxsec integer,
    call_usage integer,
    packet_count integer,
    media_packet_count integer,
    skip_packet_count integer,
    jitter_packet_count integer,
    dtmf_packet_count integer,
    cng_packet_count integer,
    flush_packet_count integer,
    largest_jb_size integer,
    jitter_min numeric,
    jitter_max numeric,
    jitter_loss_rate numeric,
    jitter_burst_rate numeric,
    mean_interval numeric,
    flaw_total integer,
    quality_percentage numeric,
    mos numeric,
    error_period_msec integer,
    gps character varying(32)
);

CREATE INDEX cdrs_ts_ind ON cdrs USING btree (ts);
