/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyCall_H_
#define	_MyCall_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum MyCall_PR {
	MyCall_PR_callId,	/* Member callId is present */
} MyCall_PR;

/* MyCall */
typedef struct MyCall {
	OCTET_STRING_t	 callId;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pMyCall, MyCall_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyCall_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyCall;

#ifdef __cplusplus
}
#endif

#endif	/* _MyCall_H_ */
#include <asn_internal.h>
