/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyE164Number_H_
#define	_MyE164Number_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum MyE164Number_PR {
	MyE164Number_PR_e164,	/* Member e164 is present */
} MyE164Number_PR;

/* MyE164Number */
typedef struct MyE164Number {
	OCTET_STRING_t	 e164;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pMyE164Number, MyE164Number_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyE164Number_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyE164Number;

#ifdef __cplusplus
}
#endif

#endif	/* _MyE164Number_H_ */
#include <asn_internal.h>
