/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyRequestBalance_H_
#define	_MyRequestBalance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MyE164Number.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyRequestBalance */
typedef struct MyRequestBalance {
	MyE164Number_t	 callingNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyRequestBalance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyRequestBalance;

#ifdef __cplusplus
}
#endif

#endif	/* _MyRequestBalance_H_ */
#include <asn_internal.h>
