/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyCC"
 * 	found in "../MyCC.asn1"
 */

#ifndef	_MyRequestMaxsec_H_
#define	_MyRequestMaxsec_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MyCall.h"
#include "MyE164Number.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyRequestMaxsec */
typedef struct MyRequestMaxsec {
	MyCall_t	 callId;
	MyE164Number_t	 callingNumber;
	MyE164Number_t	 calledNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyRequestMaxsec_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyRequestMaxsec;

#ifdef __cplusplus
}
#endif

#endif	/* _MyRequestMaxsec_H_ */
#include <asn_internal.h>
