#!/usr/bin/php -q
<?php

 include("config.app.php");

 if(!empty($argv[1])) $opt = $argv[1];
 else {
	 echo "\nChoise from follow options:\n";
	 echo "  -f filename ,importing tariff settings from file;\n";
	 echo "  -d ,dumping bplan settings from db;\n";
	 echo "  -t ,Rating functions testing;\n";
	 echo "  -p ,Rating performance testing;\n";
	 exit;
 }
 
 switch($opt) {
	case '-f':
		/* Importing new tariff plan in the DB */
		if(!empty($argv[2])) {
			re6_import_settings($argv[2]);
		} else echo "\n\tYou havent't got a input file!\n\n";
		break;
	case '-d':
		/* Dump define tariff plan(as argv[2]) from the DB */
		if(!empty($argv[2])) {
			re6_dump_bplan_settings($argv[2]);
		} else echo "\n\tYou havent't got a input 'bill plan'!\n\n";
		break;
	case '-t':
		break;
	case '-p':
		break;
	default:
		exit;
 }

?>
