#!/bin/sh
#
# This is RateEngine5 script
#
# version : 0.1
# date    : 2013-02-01
# creator : Dimitar Kokov
# e-mail  : d_kokov@abv.bg
#
# version : 0.1.1
# date    : 2015-02-27
#
# version : 0.1.2
# date    : 2015-08-25
#
# new function re5_status()
#
# version : 0.1.2.1
#
# change 'RateEngine5' as name with 'RateEngine'
#

FUNC="/etc/init.d/functions"
APP_DIR="/usr/local/RateEngine/"
CLI=$APP_DIR"bin/RateEngine"
CONF=$APP_DIR"conf/RateEngine6.xml"

if [ -f $FUNC ]
then
    . $FUNC
fi

check_app_path()
{
    if [ -d $APP_DIR ]
    then
        return 0
    else
        echo "Don't have a correct application path($APP_DIR)!"
        exit
    fi
}

check_conf_file()
{
    if [ -f $CONF ]
    then
        return 0
    else
        echo "Don't have a config file or config file path($CONF) is not correct!"
        exit
    fi
}

limits() 
{
    ulimit -c unlimited
    ulimit -d unlimited
    ulimit -f unlimited
    ulimit -i unlimited
    ulimit -u unlimited
    ulimit -v unlimited
    ulimit -x unlimited
    ulimit -l unlimited
}

start()
{
    limits
    check_app_path
    check_conf_file
    $CLI -c $CONF -d 2>&1 > /dev/null
}

stop()
{
    $CLI -c $CONF -k 2>&1 > /dev/null
}

re5_status()
{
    PID=`ps aux | grep "RateEngine" | grep ".xml" | awk -F" " '{print $2}'`

    if [ "$PID" = "" ]
    then
	echo "RateEngine is stopped"
    else
	echo "RateEngine (pid "$PID") is running..."
    fi
}

case "$1" in
    status)
	re5_status
        ;;
    start)
        start
        ;;
    stop)
        stop
    ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
esac
