#!/bin/sh
#
# It's Asterisk AGI script
#
# version : 0.4.7 
# date: 2011-09-14 
# creator: Dimitar Kokov 
# e-mail: d_kokov@abv.bg

ENGINE_HOST="localhost"
ENGINE_PORT="9090"
ENGINE_COMM="maxsec"

CALL_CONTROL_CLIENT="./2cclient"

CDR_SERVER_ID=3

CLG=$1
CLD=$2
CALL_UID=$3

COMMAND="$CALL_CONTROL_CLIENT $ENGINE_HOST $ENGINE_PORT $CDR_SERVER_ID,$ENGINE_COMM,$CLG,$CLD,$CALL_UID"

ms=`$COMMAND`
echo "SET VARIABLE maxsec "$ms
